language: node_js

node_js:
  - '7'
  - '4'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: npm
  email: iegoroff@gmail.com
  api_key:
    secure: >
      QdR269s/PgzXLBd+wogUQjLkRoSKvWppOCaML1g4ijO7iHSaZ55GgW0UTo3CcbqaMhBlJ3gkAV+uUY5doFhoeVj2Pjy7NXTE7kNnq7RHBfFEPONp3
      8r8wnslTYfEfGR3SNtNVEufYYj8kQKt/Ls9hTyG2ZlGW3qO3hOMVrQVgI521F8HNvYlnDVyIHxgi0TmRp28q5CoLH0BkEX3PeSs9NK8QPMbvczv4t
      +E1UMlyYKES2HjiKIuobNUwjlbLLq5GioVUxQsO0Z2yxqGRBJuQ3IeG4zxwh8IgMViW7AzD8AWmenLYB2apfJZRIEgCK7BttRkJr6Ex+dQxwRFzkK
      0tfWbj5g6Wh/RNU19FnXjZIpLOGl5CzQ4df+liOSNnt4Qf8FToMewdTq0Gch1AfQW/GCcWFaPetcKYpYfq/bhxHUchyHPVNngrVtxiJ3YMzFrNY2i
      f84Ax11fJWwOI5Xegu7pjGfivumBKUdl0qctwsjEP8uC6kf7HoMMP/ek5l2reNu1KRTGIgS0hy8TTDqOLEyLssg+SzJQCtByzIVf/rO8/vVffi3XS
      AnvGJv/7969lfaPmVrYu6DPDO7LCh4yg7TdxVB20oagWqCRR3YAL40POqPahZVlp0nO9tlX/bh1Ad62Xzg/RQX9u7oCY6zbm6rubHMS4a1uPq0phy
      F8Eh0=
  on:
    tags: true

script:
  npm run lint && npm test

after_script:
  npm run coverage